--- #YAML:1.0
name:               Object-Tiny-Lvalue
version:            1.06
abstract:           An lvalue accessor maker with as little code as possible
author:
    - Adam Kennedy <adamk@cpan.org>, ::Lvalue fork by Aristotle Pagaltzis
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
